### ISSUE TITLE
Player Queue

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bmm-web#102]

**Comment by u12206050** [comment]
ok :)

**Comment by u12206050** [comment]
PR: #104

**Comment by andreasgan** [comment]
https://uservoice.bcc.no/posts/60/have-a-proper-add-to-queue-function
https://uservoice.bcc.no/posts/147/queue-edit-a-queue-like-spotify

I think it's a good idea to look at how spotify does queue and try to replicate the most important bits of it.

1. "Add to queue" not "play next"
![image](https://user-images.githubusercontent.com/727125/236549962-2050d8fd-8d94-486b-98f7-23b517d3fd55.png)

2. The manually queued items is locked in place / stored in its own array. The rest of the queue is dynamic and adapts based on context (playlist, album, radio) and settings (shuffle, repeat).

https://user-images.githubusercontent.com/727125/236550657-eacafaed-ca12-4f2f-afc6-61c2fccce176.mov

**Comment by SimonSimCity** [comment]
Here's a queue-concept reguarding YT-Music.

__YT-Music__:
The player has one queue in shuffled and unshuffled version, which follow a simple set of rules: When selecting a track of a playlist or album, the queue is replaced by this list and the selected item is played. You can scroll up the queue (current track is on top of screen) to see the ones in the list which were above the one you're playing (either the ones you listened to or the ones over the one in the actual list). When adding a single track or album, it is added always right after the one currently playing (regardless of whether the list is shuffled). When shuffling the list, all tracks in the queue (even the ones of your history) are shuffled (and reshuffled if you had it shuffled earlier - a shuffled version doesn't need to be stored after unshuffling). If a song or album is added in the shuffled version, it is also added at the end of the queue in the unshuffled version.

When selecting an item off the search, it only plays the selected song.

Autoplay always kicks in after the list is finished (unlike BMM, where it only applies to "Fra Kåre", well actually it applies to all cards on the discover view, even audiobooks where it only plays the current chapter and continues with songs...) - maybe good to get something better here...

Can someone who has Spotify please confirm how they have managed queuing? If I remember right, Spotify doesn't always add after the currently playing one, right? E.g. when adding two tracks individually as "play next", in YT-Music the one added latest would be played first, because you wanted it to be played _next_.

**Comment by SimonSimCity** [comment]
Further conceptional differences in the player of YT-Music and Spotify:

**Replacing the queue:**

*YT-Music:*
When you replace the queue (e.g. by tapping on a song in the search, or playing an album), the whole queue is replaced.

*Spotify:*
When replacing the queue, only the regular play queue is replaced, the "play it first" queue stays unchanged. The currently playing song is replaced by the selected song, after which the player continues with the "play it first" queue after which it continues with the rest of the playlist/album/etc.

**Shuffle:**

*YT-Music:*
When enabling shuffle, it only yields for the queue. When selecting an album to play, the shuffle mode is reset.

*Spotify:*
When enabling shuffle, it can be seen as a mode. When selecting an album to play, the shuffle mode is not reset, but the album will start playing from a random position. This even yields for audio-books.

*My preference:* As YT-Music, because we have content which you'd like to listen to in its chronological order (recordings of meetings or even more important for audio-books).

Some additional resource to spotify's shuffle algorithm, which is *quite* special: https://medium.com/immensity/how-spotifys-shuffle-algorithm-works-19e963e75171

**Comment by andreasgangso** [comment]
Remember that this is a UX decision, so @sclausendk should be involved

**Comment by Ghostbird** [comment]
Personally one of the things I find most annoying in BMM is that it often queues too much. Such as when you search and tap to play a single song, it adds all search results.

When you pick a song in an album, it queues the remainder of the album. Sometimes I do want that, but sometimes it's really annoying.

**Comment by SimonSimCity** [comment]
@Ghostbird 

> Personally one of the things I find most annoying in BMM is that it often queues too much. Such as when you search and tap to play a single song, it adds all search results.

I agree, that's too much and not in line with what other players are doing.

> When you pick a song in an album, it queues the remainder of the album. Sometimes I do want that, but sometimes it's really annoying.

Well, that again is in line with what other players do. Would be good if you could differentiate between those two cases. Most players have an `Add to queue` and/or `Add next` option, if you do not want to replace the queue by the item and the album you just tapped at.

While there is an open user-voice entry by me (see my comment above), this is very much for @sclausendk to give an answer to.
