### ISSUE TITLE
Milestones / Roadmap

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bmm-web#154]
This is a list of milestones which I would suggest. The idea is to have a focus and know what to prioritize next.
I think it makes sense to focus on playing music first and focus on making bmm-web useful while working. Once v0.1 is reached we could post it on Discord and have developers try the alpha version.

The order is not set in stone and subject to change.

- v0.1 - Play music
  - #8 
  - #66 
  - #136
  - #153 
  - #162 
- v0.2 - Media Player
  - #65
- v0.3 - Edit Personal Playlists
  - #198
  - #200
- v0.4 - Search, Share
  - #49
  - #199
- v0.5 - Everything on Homescreen
  - #194
- v0.6 - Streak
  - collect listening data & send to server
  - show streak on homescreen
- v0.7 - Transcription & Lyrics
  - jump to position
  - show transcriptions & lyrics
- v0.8 - Advanced Queue
- ...

**Comment by kkuepper** [comment]
@SimonSimCity @sifferhans What do you think? Do you have feedback?

**Comment by sifferhans** [comment]
Looks good 👍🏼 What's the "profile" point in v0.1?

**Comment by SimonSimCity** [comment]
To me `v0.1` should not only include `expand player`, which to me is just finishing #65, but also a proper queue mechanism, #102, which you wanted to address in `v0.5`. If those are meant different, please elaborate.

I guess `Profile` is #8? If yes, please update.

Is *jump to position* in `v0.4` to jump to a position of a track? If yes, where and how would this be used?

Can you please also create tickets for *collect listening data & send to server* and *show Tiles & streak on homescreen* of `v0.2`, where you explain a bit how that can be accomplished? Otherwise those tasks are unclear to me and I'd have to start investigating in the bmm-app to see how you've done it there, but might not be able to find concepts and thoughts behind the implementation.

**Comment by sifferhans** [comment]
Should we use Discussions for these things? (Roadmap, milestones etc)

**Comment by kkuepper** [comment]
I think v0.1 needs to have a way to skip to the next song. When I use the current version, that's the most annoying missing feature right now. Since that button is part of #65 it should be in v0.1. But to have a full-fledged queue is not part of v0.1.

Updated profile to #8.

Part of the transcription search is that you can jump to the part of a message (see app). So to properly support transcription search, jump to position needs to be implemented.

About Tiles & streak it probably makes sense that I carve out some time, to implement it. That's why I haven't created issues for it yet.

**Comment by SimonSimCity** [comment]
Moved discussion over to https://github.com/bcc-code/bmm-web/discussions/156
