### ISSUE TITLE
Add `lint-staged` auto-lint and fixes

### ISSUE THREAD

**Issue by Ghostbird** [bcc-code/bmm-web#203]
This will make committing a bit slower, but it will ensure that all commits are formatted according to ESLint and Prettier rules. The advantage is that you won't run into PRs that fail to build, simply because someone forgot to add a newline to the end of the file, etc.

**Comment by SimonSimCity** [comment]
I'd rather avoid adding this, because it makes committing slower. To me this falls into the category of not running your tests before committing. Our setup should be set up in a way that editing files outside the editor is an exception, for which the user is responsible himself to handle it.

If you change files outside the editor, please run the linter yourself. I don't want to make everyones experience worse by handling a few exceptions - that's my opinion on this. If there's nothing against it, I'd close this issue as "wont-implement".

**Comment by Ghostbird** [comment]
This is not about changing file _outside the editor_, this is just about changing files at all. Personally I like it for the reason that it saves me from the occasional failed build, due to linter checks. Having to wait for a failed CI‌ build and fixing that is in my opinion far more annoying than having to wait a few extra seconds on a commit, for a guard to check whether my changes pass linting. However, I can just set it up locally.
