### ISSUE TITLE
Home page doesn't load (new elements lead to exception)

### ISSUE THREAD

**Issue by sifferhans** [bcc-code/bmm-web#270]
The home page doesn't load.
![CleanShot 2024-01-17 at 12 23 36@2x](https://github.com/bcc-code/bmm-web/assets/18753964/65ab7da2-558b-4661-8818-dc40ef8549e1)

**Comment by SimonSimCity** [comment]
Seems to be fixed without any focus applied to it ... Maybe the PR #269 did something, but otherwise I don't know ... @kkuepper do you know about anything that was changed to get this working again?

**Comment by kkuepper** [comment]
I didn't notice there was an issue about it.

I disabled the project-box for the website.
(Detailed explanation: I added a MinVersion to the project-box element. Since the Website doesn't send an app version, the website doesn't get the project-box in the discover request anymore.)

That does highlight 2 problems though:

1. If a new unknown element is added, the website should just ignore it and not throw an error that prevents the whole list from being shown.
2. I don't know how to update bmm-fetch so that the website knows about the new element. Actually it's only @SimonSimCity that knows how to do that. The best would be to have a github action that creates a new package version automatically.

**Comment by SimonSimCity** [comment]
IMO, solving 2) would just shorten the time of an error like this to be fixed, whereby 1) would prevent it in the first run from happening. This said, 1) should have the focus here.

Issue 1) should be fixed by #33, and 2) there's not anything more to it than running the 3 commands described in the readme of the package (https://github.com/bcc-code/bmm-sdk).

But this always also depends on how strong the structure of the backend is changed. If there's something which has been replaced, this might eventually pose some issues - same as if data is not according to the specs - the swagger file.
