### ISSUE TITLE
AppId and Product name

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bmm-web#280]
<img width="219" alt="Screenshot 2024-02-06 at 3 56 25 PM" src="https://github.com/bcc-code/bmm-web/assets/649978/214518d0-ecff-4fa4-9617-ca93eacdcf5a">

Since we want to start rolling out bmm-web, it makes a lot of sense to have auto-updates working. The easiest is to use Electron Builder autoUpdate and Github releases. Since the auto-update process uses the appId and product name to build the urls, we should decide now what the final values will be.

I suggest media.bcc.bmm-web as appId and BMM as product name.

@SimonSimCity @KillerX @andreasgangso
Can you please comment that you're fine with that or come with feedback.

**Comment by SimonSimCity** [comment]
LGTM. I don't really have a stake on what `appId` is, but the product name is the name the app will appear in the app-store, right? The mobile app has the name "BMM Brunstad" in the app-store - would be good to have this aligned - either the same or showing the difference, IMO.

**Comment by kkuepper** [comment]
I thought to distribute it not through the app store. Just have a download page on the website that links to the file on Github releases. The user would need to install it once and after that it will auto-update itself.

<img width="269" alt="Screenshot 2024-02-07 at 7 27 44 AM" src="https://github.com/bcc-code/bmm-web/assets/649978/0417918b-9768-48b6-a324-faa313a94c27">
The disadvantage is that users get this warning message. But I think it would be fine. (Windows shows a similar message. Maybe even more aggressive.)

**Comment by andreasgangso** [comment]
lgtm
I noticed dashes are bad for mobile app identifiers because of differing standards on ios/android. Ios only accepts -, android only _.

But thats not a problem here

**Comment by kkuepper** [comment]
We could consider "bcc.media.bmm" instead of "media.bcc.bmm".

**Comment by KillerX** [comment]
The warning can be avoided but it's not a super pretty process:

Mac: https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow 

Win: https://learn.microsoft.com/en-us/windows/win32/seccrypto/signtool

Summary of both:
https://gist.github.com/Jolg42/201f75a3699f5742a9605170dc50bfbc

**Comment by kkuepper** [comment]
We already notarize the Mac dmg.

For Windows the question is where to get the certificate. The [Electron Builder documentation](https://www.electron.build/code-signing#where-to-buy-code-signing-certificate) makes it sound like you need to buy it. It costs ~$1000 per year.

**Comment by KillerX** [comment]
> We already notarize the Mac dmg.
> 
> For Windows the question is where to get the certificate. The [Electron Builder documentation](https://www.electron.build/code-signing#where-to-buy-code-signing-certificate) makes it sound like you need to buy it. It costs ~$1000 per year. (Jolg42 recommends [ksoftware](https://www.ksoftware.net/code-signing-certificates/) which costs $313)

I am not averse to spending up to ~500 USD on this for a year to at the very least test the impact. 
The issue is imo that we should have a EV and as far as I understand they are only provided in HSM (usb thingy). This makes the whole thing so much more complex for "security theater" reasons.

So there are 2 main options on windows: 

* Get a cert on a stick and run a custom GH runner locally in Moss. Doable, we have docker and VM options that can be isolated from the rest of the network easily.
* Use the cloud options. They tend to have limited signings and tend to cost more than the cert itself.\

Should we give it a shot with a https://www.ssl.com/certificates/ev-code-signing/ and a Self hosted runner?
I have approval to order this package:

![image](https://github.com/bcc-code/bmm-web/assets/398737/c6abddaa-4efe-4e68-8555-12b3c5dac1dc)
