### ISSUE TITLE
setup a formatting config

### ISSUE THREAD

**Issue by bjornarhagen** [bcc-code/bmm-web#90]
Currently the formatting is handled by Prettier.
But we do not have any config file that defines what the formatting should be, so it uses the default.

The problem with this is that developers might have changed their default. Also the default might be different between different versions of Prettier.

If we setup a .prettierrc file in the root folder, Prettier will use that instead of the default.

Also a suggestion, the default line width of 80 is very short, we should set it to 120-140, the HTML/Vue template becomes much more readable.

**Comment by sifferhans** [comment]
Yeah, this has been a pain point for me, as I have had some custom prettier settings

**Comment by SimonSimCity** [comment]
Thanks very much for letting me know about your pain points 😃 I tried to address them by adding an empty `.prettierrc` file, as mentioned in the docs of the prettier plugin for vscode (https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode#visual-studio-code-settings).

> Also the default might be different between different versions of Prettier.

This should be quite unrelated to our project, because we've fixed the version of prettier we're using.

> Also a suggestion, the default line width of 80 is very short, we should set it to 120-140, the HTML/Vue template becomes much more readable.

I would personally stick to what prettier defines. Its opinionated, yes, but that's why we chose a tool for that, right? Btw, the default line width is preferred, not strict (https://prettier.io/docs/en/options.html#print-width)
